sonar.projectKey=aceest-gym
sonar.projectName=aceest-gym
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=squ_293a95dd13e457e9042528092b9f6b5b88169573